### ISSUE TITLE
It fails when using with clang

### ISSUE THREAD

**Issue by pan3rock** [jamadagni/toms748#1]
Thanks for this useful implement of toms748 for avoiding the import of Boost library. I encounter a weird problem: I compile it with gcc, it works, but fails with clang. It return error_code 128. I print the variable in toms748.cc and find  `c` is nan when it fails. I don't understand why the different compiler will lead to different results. Do you have any idea?

**Comment by jamadagni** [comment]
Hello. I also use Clang. I don't find any problem:

    $ C=clang CXX=clang++ make
    cd tests && /usr/bin/clang++ -DTOMS748 -o toms748-tests tests.cpp ../toms748.cpp -I.. && echo "Running TOMS748 tests" && ./toms748-tests > toms748-tests.out.txt
    Running TOMS748 tests
    cd tests && /usr/bin/clang++ -DBISECTION -o bisection-tests tests.cpp bisection.cpp -I.. && echo "Running bisection tests for comparison" && ./bisection-tests > bisection-tests.out.txt
    Running bisection tests for comparison
    /usr/bin/clang++ -c toms748.cpp
    cd examples && /usr/bin/clang -o example_c example.c elliptic_integral.c ../toms748.o -lm && echo "Running C example" && ./example_c
    Running C example
    63.944963
    cd examples && /usr/bin/clang++ -o example_cpp example.cpp elliptic_integral.c ../toms748.o -lm && echo "Running C++ example" && ./example_cpp
    clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
    Running C++ example
    63.944963

Right now I am running Clang 14 on Kubuntu Jammy (22.04) but the library was developed using an earlier version (I don't have access to that computer right now so don't remember the Clang version) on Kubuntu Focal (20.04). So I don't understand why this should be so. Please do update if you investigate this further.

**Comment by pan3rock** [comment]
I have found the problem. I'm used to add '-O2' or '-O3' and the wrong result occurs when the optimize flag is opened. I print all variable in the process and find fd will be initialized with nan (I don't know why) that leads to a nan value of c (fd -> fe -> c). 

It can be fixed by an explicit initalization.

```c++
  Toms748Solver(Toms748InputFunction function, void *otherInput,
                double intervalStart, double intervalEnd,
                Toms748ResultStatus *resultStatus, double absoluteTolerance,
                double relativeTolerance, int maximumIterations,
                int interpolationsPerIteration)
      : f{function}, args{otherInput}, a{intervalStart}, fa{0.0},
        b{intervalEnd}, fb{0.0}, c{0.0}, fc{0.0}, d{0.0}, fd{0.0}, e{NAN},
        fe{0.0}, u{0.0}, fu{0.0}, stat{resultStatus},
        areClose{absoluteTolerance, relativeTolerance},
        maxiter{maximumIterations}, remiter{maximumIterations}, fncount{0},
        k{interpolationsPerIteration}
{
...
}
```
My clang version is 13.0.1, it may be just the problem of this version.

**Comment by jamadagni** [comment]
Hello. Just checked using -O2 and -O3. (By “optimize flag” is opened I suppose you mean when it is used.) However I do not find the error with the current code. Are you using any other flags?

I thought I faithfully copied the algorithm from Boost and only factorized it somewhat to cleanup and added the specialities from SciPy. But I now find that in Boost there is a default initialization which I have not copied:

    // dummy value for fd, e and fe:
    fe = e = fd = 1e5F;

Can you try adding this line above the comment “first iteration” and check?

**Comment by pan3rock** [comment]
I build my program through CMake, and only use `set(CMAKE_CXX_FLAGS "-O3")`. After adding this line, the result is OK even if using -O2 or -O3. It seems to be the uninitialized problem.

**Comment by jamadagni** [comment]
Thanks for your feedback. 

I note that setting `e` to `1e5` undermines the current methodology of setting `e` to `NAN` to force initial step of second iteration to be quadratic. Is it possible to avoid setting `e` and set `fd` and `fe` only?

Would be good if I could reproduce your problem myself so I don't have to bother you for testing. Do you mind sharing a minimum example? Thanks.

**Comment by jamadagni** [comment]
Hello. @pan3rock can you please share a minimum example? I'm working on the code. It would be helpful. Thanks.

**Comment by pan3rock** [comment]
Sorry for the late reply. I'm afraid to provide an example to reproduce this problem, because it is combined with a complicated solver of my research. I test the case that e=NAN, fd=fe=1e5 and it also works.  Hope this helps.

**Comment by jamadagni** [comment]
Hello. @pan3rock can you please check whether the current version fixes the issue as intended?
